site_name: Zigma360 TechDoc
copyright: Copyright &copy; 2021 Zigma360
#repo_url: https://git.zigma360.com/projects/ZIG/repos/zigma360/browse
#repo_name: zigma360

nav:
    - Home: 'index.md'
    - 'Git':
      - git/index.md
      - 'Installation': 'git/installation.md'
      - 'Zigma360 git workflow': 'git/zigma360-git-workflow.md'
      - 'Git Commands': 'git/git-commands.md'
      - 'Undoing Changes': 'git/undoing-changes.md'
    - 'How-To':
      - 'Zigma cloud certificate': 'how-to/cloud-wildcard-certificate.md'
      - 'Porting Projects to .NET 6': 'how-to/porting-csproject-to-net6.md'
    - About:
      - about/index.md
      - 'Getting started': 'about/getting-started.md'
      - 'User Guide':
        - 'Writing Your Docs': 'https://www.mkdocs.org/user-guide/writing-your-docs/'
        - 'Syntax Reference': 'https://squidfunk.github.io/mkdocs-material/reference/abbreviations/'
        - 'Deploying Your Docs': 'https://www.mkdocs.org/user-guide/deploying-your-docs/'

extra:
  social:


theme:
    name: material
    highlightjs: true
    suppress_nextprev: false

    palette:
      - scheme: default
        toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
      - scheme: slate
        toggle:
          icon: material/weather-night
          name: Switch to light mode

    features:
      - header.autohide
      - navigation.tabs
      - navigation.sections
      - navigation.indexes
      - content.code.annotate
      - announce.dismiss

    icon:
      repo: fontawesome/brands/bitbucket

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - tables
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - meta
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 3
